// src/lib/optionLabels.js
//
// Translated display labels for dropdown/chip OPTIONS whose underlying
// VALUE must stay a stable English string (it's what gets sent into the
// AI prompt as a category label, e.g. groupType: "Adults"). Only the
// label shown to the user changes with the language — the value saved
// to state, sent to the API, and stored on saved records is untouched.
//
// Lookup is safe by design: if a language or a specific option is not
// translated below, translateOption() falls back to the original English
// string, so nothing ever renders blank.
//
// NOTE: fr/es entries are translated with confidence. yo (Yoruba), ig
// (Igbo) and pcm (Nigerian Pidgin) entries are a best-effort pass using
// common church/devotional vocabulary — flagged here for a native-speaker
// review pass before this ships to end users, same as the rest of the
// app's yo/ig/pcm dictionary.

export const OPTION_LABELS = {
  sermonAudience: {
    fr: {
      'General congregation': 'Assemblée générale',
      'Youth service': 'Culte des jeunes',
      'Leaders & ministers': 'Responsables et ministres',
      "Women's meeting": 'Réunion des femmes',
      'Evangelistic / outreach': 'Évangélisation',
      'Children / Sunday school': 'École du dimanche',
      'New believers': 'Nouveaux croyants',
      'Funeral service': 'Service funèbre',
      'Wedding service': 'Cérémonie de mariage',
      'Bible study': 'Étude biblique',
    },
    es: {
      'General congregation': 'Congregación general',
      'Youth service': 'Servicio juvenil',
      'Leaders & ministers': 'Líderes y ministros',
      "Women's meeting": 'Reunión de mujeres',
      'Evangelistic / outreach': 'Evangelismo',
      'Children / Sunday school': 'Escuela dominical',
      'New believers': 'Nuevos creyentes',
      'Funeral service': 'Servicio funerario',
      'Wedding service': 'Ceremonia de boda',
      'Bible study': 'Estudio bíblico',
    },
    pcm: {
      'General congregation': 'General congregation',
      'Youth service': 'Youth service',
      'Leaders & ministers': 'Leaders & ministers',
      "Women's meeting": 'Women meeting',
      'Evangelistic / outreach': 'Evangelism / outreach',
      'Children / Sunday school': 'Children / Sunday school',
      'New believers': 'New believers',
      'Funeral service': 'Funeral service',
      'Wedding service': 'Wedding service',
      'Bible study': 'Bible study',
    },
    yo: {
      'General congregation': 'Ìjọ gbogbogbò',
      'Youth service': 'Ìsìn àwọn ọ̀dọ́',
      'Leaders & ministers': 'Àwọn olùdarí àti òjísìn',
      "Women's meeting": 'Ìpàdé àwọn obìnrin',
      'Evangelistic / outreach': 'Ìwàásù ìtànkálẹ̀',
      'Children / Sunday school': 'Ilé-ìwé Ọjọ́ Ìsinmi',
      'New believers': 'Àwọn onígbàgbọ́ tuntun',
      'Funeral service': 'Ìsìn ìsìnkú',
      'Wedding service': 'Ìsìn ìgbéyàwó',
      'Bible study': 'Ìkẹ́kọ̀ọ́ Bíbélì',
    },
    ig: {
      'General congregation': 'Nzukọ n\u2019ozuzu',
      'Youth service': 'Ọrụ ndị na-eto eto',
      'Leaders & ministers': 'Ndị ndu na ndị ozi',
      "Women's meeting": 'Nzukọ ụmụ nwanyị',
      'Evangelistic / outreach': 'Ozi ọma / mbasa',
      'Children / Sunday school': 'Ụlọ akwụkwọ ụbọchị ụka',
      'New believers': 'Ndị kwere ekwe ọhụrụ',
      'Funeral service': 'Ememe olili ozu',
      'Wedding service': 'Ememe agbamakwụkwọ',
      'Bible study': 'Ọmụmụ Akwụkwọ Nsọ',
    },
  },
  sermonDenomination: {
    fr: {
      'Pentecostal / Charismatic': 'Pentecôtiste / Charismatique',
      'Anglican / Episcopal': 'Anglicane / Épiscopale',
      Baptist: 'Baptiste',
      'Catholic-friendly': 'Compatible catholique',
      Evangelical: 'Évangélique',
      Teaching: 'Enseignement',
      Prophetic: 'Prophétique',
      'Youth-friendly': 'Adapté aux jeunes',
    },
    es: {
      'Pentecostal / Charismatic': 'Pentecostal / Carismática',
      'Anglican / Episcopal': 'Anglicana / Episcopal',
      Baptist: 'Bautista',
      'Catholic-friendly': 'Afín a lo católico',
      Evangelical: 'Evangélica',
      Teaching: 'Enseñanza',
      Prophetic: 'Profética',
      'Youth-friendly': 'Orientada a jóvenes',
    },
    pcm: {},
    yo: {
      'Pentecostal / Charismatic': 'Pentikọsti / Aládàárà',
      'Anglican / Episcopal': 'Ṣọ́ọ̀ṣì Áńgílíkàn',
      Baptist: 'Ṣọ́ọ̀ṣì Bátìsì',
      'Catholic-friendly': 'Ó bá ti Kátólíìkì mu',
      Evangelical: 'Ajíhìnrere',
      Teaching: 'Ẹ̀kọ́',
      Prophetic: 'Àsọtẹ́lẹ̀',
      'Youth-friendly': 'Ó bá àwọn ọ̀dọ́ mu',
    },
    ig: {
      'Pentecostal / Charismatic': 'Pentikọstal / Charismatic',
      'Anglican / Episcopal': 'Ụka Angican',
      Baptist: 'Ụka Baptist',
      'Catholic-friendly': 'Kwekọrọ na Katọlik',
      Evangelical: 'Ndị nkwusa ozi ọma',
      Teaching: 'Ozizi',
      Prophetic: 'Amụma',
      'Youth-friendly': 'Kwekọrọ na ndị na-eto eto',
    },
  },
  sermonLength: {
    fr: {
      '10-minute message': 'Message de 10 minutes',
      '20-minute message': 'Message de 20 minutes',
      '30-minute message': 'Message de 30 minutes',
      '45-minute sermon': 'Sermon de 45 minutes',
      '60-minute sermon': 'Sermon de 60 minutes',
    },
    es: {
      '10-minute message': 'Mensaje de 10 minutos',
      '20-minute message': 'Mensaje de 20 minutos',
      '30-minute message': 'Mensaje de 30 minutos',
      '45-minute sermon': 'Sermón de 45 minutos',
      '60-minute sermon': 'Sermón de 60 minutos',
    },
    pcm: {},
    yo: {
      '10-minute message': 'Ọ̀rọ̀ ìṣẹ́jú 10',
      '20-minute message': 'Ọ̀rọ̀ ìṣẹ́jú 20',
      '30-minute message': 'Ọ̀rọ̀ ìṣẹ́jú 30',
      '45-minute sermon': 'Ìwàásù ìṣẹ́jú 45',
      '60-minute sermon': 'Ìwàásù ìṣẹ́jú 60',
    },
    ig: {
      '10-minute message': 'Ozizi nkeji iri',
      '20-minute message': 'Ozizi nkeji iri abụọ',
      '30-minute message': 'Ozizi nkeji iri atọ',
      '45-minute sermon': 'Nkwusa nkeji iri anọ na ise',
      '60-minute sermon': 'Nkwusa otu awa',
    },
  },
  sermonTone: {
    fr: { Teaching: 'Enseignement', Inspirational: 'Inspirant', Evangelistic: 'Évangélique', Pastoral: 'Pastoral', Revival: 'Réveil' },
    es: { Teaching: 'Enseñanza', Inspirational: 'Inspirador', Evangelistic: 'Evangelístico', Pastoral: 'Pastoral', Revival: 'Avivamiento' },
    pcm: {},
    yo: { Teaching: 'Ẹ̀kọ́', Inspirational: 'Amúnilọ́kànyọ̀', Evangelistic: 'Ìhìnrere', Pastoral: 'Ìsọ́dẹ̀', Revival: 'Ìjí ẹ̀mí' },
    ig: { Teaching: 'Ozizi', Inspirational: 'Na-akpali obi', Evangelistic: 'Ozi ọma', Pastoral: 'Nchụzi', Revival: 'Mmụọ Nsọ mgbake' },
  },
  studyGroupType: {
    fr: {
      'Youth (13-25)': 'Jeunes (13-25)',
      Adults: 'Adultes',
      'New believers': 'Nouveaux croyants',
      'Workers/Professionals': 'Travailleurs/Professionnels',
      Leaders: 'Responsables',
      'Mixed congregation': 'Assemblée mixte',
      Children: 'Enfants',
      'Senior adults': 'Aînés',
    },
    es: {
      'Youth (13-25)': 'Jóvenes (13-25)',
      Adults: 'Adultos',
      'New believers': 'Nuevos creyentes',
      'Workers/Professionals': 'Trabajadores/Profesionales',
      Leaders: 'Líderes',
      'Mixed congregation': 'Congregación mixta',
      Children: 'Niños',
      'Senior adults': 'Adultos mayores',
    },
    pcm: {},
    yo: {
      'Youth (13-25)': 'Ọ̀dọ́ (13-25)',
      Adults: 'Àgbàlagbà',
      'New believers': 'Onígbàgbọ́ tuntun',
      'Workers/Professionals': 'Òṣìṣẹ́/Akọ́ṣẹ́mọṣẹ́',
      Leaders: 'Olùdarí',
      'Mixed congregation': 'Ìjọ àdàpọ̀',
      Children: 'Ọmọdé',
      'Senior adults': 'Àgbàlagbà àgbà',
    },
    ig: {
      'Youth (13-25)': 'Ndị na-eto eto (13-25)',
      Adults: 'Ndị okenye',
      'New believers': 'Ndị kwere ekwe ọhụrụ',
      'Workers/Professionals': 'Ndị ọrụ/Ọkachamara',
      Leaders: 'Ndị ndu',
      'Mixed congregation': 'Nzukọ agwakọta',
      Children: 'Ụmụaka',
      'Senior adults': 'Ndị okenye kacha',
    },
  },
  studyLength: {
    fr: { '30 minutes': '30 minutes', '45 minutes': '45 minutes', '60 minutes': '60 minutes', '90 minutes': '90 minutes' },
    es: { '30 minutes': '30 minutos', '45 minutes': '45 minutos', '60 minutes': '60 minutos', '90 minutes': '90 minutos' },
    pcm: {},
    yo: { '30 minutes': 'Ìṣẹ́jú 30', '45 minutes': 'Ìṣẹ́jú 45', '60 minutes': 'Ìṣẹ́jú 60', '90 minutes': 'Ìṣẹ́jú 90' },
    ig: { '30 minutes': 'Nkeji iri atọ', '45 minutes': 'Nkeji iri anọ na ise', '60 minutes': 'Otu awa', '90 minutes': 'Awa na ọkara' },
  },
  studyTone: {
    fr: {
      'Simple & accessible': 'Simple et accessible',
      'Deep & theological': 'Approfondi et théologique',
      Conversational: 'Conversationnel',
      'Teaching style': 'Style enseignement',
      Reflective: 'Réflexif',
    },
    es: {
      'Simple & accessible': 'Simple y accesible',
      'Deep & theological': 'Profundo y teológico',
      Conversational: 'Conversacional',
      'Teaching style': 'Estilo de enseñanza',
      Reflective: 'Reflexivo',
    },
    pcm: {},
    yo: {
      'Simple & accessible': 'Rọrùn àti wíwọlé',
      'Deep & theological': 'Jíjìn àti ti ẹ̀kọ́ ìsìn',
      Conversational: 'Ìjíròrò',
      'Teaching style': 'Ọ̀nà ẹ̀kọ́',
      Reflective: 'Ìronú jíjinlẹ̀',
    },
    ig: {
      'Simple & accessible': 'Mfe na nnweta',
      'Deep & theological': 'Miri emi na nke ozizi okpukpe',
      Conversational: 'Mkparịta ụka',
      'Teaching style': 'Ụdị ozizi',
      Reflective: 'Ntule',
    },
  },
  studyTheme: {
    fr: {
      Forgiveness: 'Pardon',
      Faith: 'Foi',
      Prayer: 'Prière',
      'Identity in Christ': 'Identité en Christ',
      Grace: 'Grâce',
      'Suffering & Hope': 'Souffrance et espérance',
      'The Holy Spirit': "L'Esprit Saint",
      Generosity: 'Générosité',
      Worship: 'Adoration',
      Discipleship: 'Discipulat',
      Love: 'Amour',
      Evangelism: 'Évangélisation',
      'Marriage & Family': 'Mariage et famille',
      Purpose: 'Dessein',
    },
    es: {
      Forgiveness: 'Perdón',
      Faith: 'Fe',
      Prayer: 'Oración',
      'Identity in Christ': 'Identidad en Cristo',
      Grace: 'Gracia',
      'Suffering & Hope': 'Sufrimiento y esperanza',
      'The Holy Spirit': 'El Espíritu Santo',
      Generosity: 'Generosidad',
      Worship: 'Adoración',
      Discipleship: 'Discipulado',
      Love: 'Amor',
      Evangelism: 'Evangelismo',
      'Marriage & Family': 'Matrimonio y familia',
      Purpose: 'Propósito',
    },
    pcm: {},
    yo: {
      Forgiveness: 'Ìdáríjì',
      Faith: 'Ìgbàgbọ́',
      Prayer: 'Àdúrà',
      'Identity in Christ': 'Ìdánimọ̀ nínú Kristi',
      Grace: 'Oore-ọ̀fẹ́',
      'Suffering & Hope': 'Ìjìyà àti Ìrètí',
      'The Holy Spirit': 'Ẹ̀mí Mímọ́',
      Generosity: 'Ọ̀làwọ́',
      Worship: 'Ìjọsìn',
      Discipleship: 'Ìjẹ́ọmọ-ẹ̀yìn',
      Love: 'Ìfẹ́',
      Evangelism: 'Ìhìnrere',
      'Marriage & Family': 'Ìgbéyàwó àti Ẹbí',
      Purpose: 'Ète',
    },
    ig: {
      Forgiveness: 'Mgbaghara',
      Faith: 'Okwukwe',
      Prayer: 'Ekpere',
      'Identity in Christ': 'Njirimara na Kraịst',
      Grace: 'Amara',
      'Suffering & Hope': 'Ahụhụ na Olileanya',
      'The Holy Spirit': 'Mmụọ Nsọ',
      Generosity: 'Imesa ebere',
      Worship: 'Ofufe',
      Discipleship: 'Ịbụ onye na-eso ụzọ',
      Love: 'Ịhụnanya',
      Evangelism: 'Ozi ọma',
      'Marriage & Family': 'Alụmdi na nwunye na Ezinụlọ',
      Purpose: 'Ebumnobi',
    },
  },
  socialPlatform: {
    fr: {
      'WhatsApp & Instagram': 'WhatsApp et Instagram',
      Facebook: 'Facebook',
      'X / Twitter': 'X / Twitter',
      'TikTok / Reels': 'TikTok / Reels',
      'All platforms': 'Toutes les plateformes',
    },
    es: {
      'WhatsApp & Instagram': 'WhatsApp e Instagram',
      Facebook: 'Facebook',
      'X / Twitter': 'X / Twitter',
      'TikTok / Reels': 'TikTok / Reels',
      'All platforms': 'Todas las plataformas',
    },
    pcm: {},
    yo: {
      'WhatsApp & Instagram': 'WhatsApp àti Instagram',
      Facebook: 'Facebook',
      'X / Twitter': 'X / Twitter',
      'TikTok / Reels': 'TikTok / Reels',
      'All platforms': 'Gbogbo pátákò',
    },
    ig: {
      'WhatsApp & Instagram': 'WhatsApp na Instagram',
      Facebook: 'Facebook',
      'X / Twitter': 'X / Twitter',
      'TikTok / Reels': 'TikTok / Reels',
      'All platforms': 'Ikpo okwu niile',
    },
  },
  socialTone: {
    fr: {
      'Warm & inviting': 'Chaleureux et accueillant',
      'Bold & powerful': 'Audacieux et puissant',
      Evangelistic: 'Évangélique',
      'Youth-friendly': 'Adapté aux jeunes',
      'Premium & polished': 'Premium et soigné',
      'Pastoral & caring': 'Pastoral et bienveillant',
    },
    es: {
      'Warm & inviting': 'Cálido y acogedor',
      'Bold & powerful': 'Audaz y poderoso',
      Evangelistic: 'Evangelístico',
      'Youth-friendly': 'Orientado a jóvenes',
      'Premium & polished': 'Premium y cuidado',
      'Pastoral & caring': 'Pastoral y afectuoso',
    },
    pcm: {},
    yo: {
      'Warm & inviting': 'Onítara àti onídùnnú',
      'Bold & powerful': 'Onígboyà àti alágbára',
      Evangelistic: 'Ìhìnrere',
      'Youth-friendly': 'Ó bá àwọn ọ̀dọ́ mu',
      'Premium & polished': 'Ọ̀ṣọ́ àti dídán',
      'Pastoral & caring': 'Ìtọ́jú olùṣọ́-àgùntàn',
    },
    ig: {
      'Warm & inviting': 'Obiọma na ịkpọ ọbịa',
      'Bold & powerful': 'Obi ike na ike',
      Evangelistic: 'Ozi ọma',
      'Youth-friendly': 'Kwekọrọ na ndị na-eto eto',
      'Premium & polished': 'Mma na nhazi',
      'Pastoral & caring': 'Nlekọta nchụzi',
    },
  },
  socialContentType: {
    fr: {
      'Sunday invitation': 'Invitation du dimanche',
      'Sermon quote': 'Citation du sermon',
      'Midweek reminder': 'Rappel de milieu de semaine',
      Encouragement: 'Encouragement',
      'Testimony prompt': "Invite au témoignage",
      'Giving reminder': 'Rappel de don',
      'Event promo': "Promo d'événement",
    },
    es: {
      'Sunday invitation': 'Invitación del domingo',
      'Sermon quote': 'Cita del sermón',
      'Midweek reminder': 'Recordatorio de mitad de semana',
      Encouragement: 'Aliento',
      'Testimony prompt': 'Invitación a testificar',
      'Giving reminder': 'Recordatorio de ofrenda',
      'Event promo': 'Promoción de evento',
    },
    pcm: {},
    yo: {
      'Sunday invitation': 'Ìkésíni ọjọ́ Ìsinmi',
      'Sermon quote': 'Àyọkà ìwàásù',
      'Midweek reminder': 'Ìrántí àárín ọ̀sẹ̀',
      Encouragement: 'Ìṣírí',
      'Testimony prompt': 'Ìpè ẹ̀rí',
      'Giving reminder': 'Ìrántí ọrẹ',
      'Event promo': 'Ìpolówó ìṣẹ̀lẹ̀',
    },
    ig: {
      'Sunday invitation': 'Ọkpụkpọ ụbọchị ụka',
      'Sermon quote': 'Okwu si na nkwusa',
      'Midweek reminder': 'Ncheta n\u2019etiti izu',
      Encouragement: 'Nkasi obi',
      'Testimony prompt': 'Ọkpụkpọ akaebe',
      'Giving reminder': 'Ncheta onyinye',
      'Event promo': 'Mgbasa ozi mmemme',
    },
  },
  fastingType: {
    fr: {
      'Partial fast (sunrise to sunset)': 'Jeûne partiel (du lever au coucher du soleil)',
      'Daniel fast (fruits & vegetables)': 'Jeûne de Daniel (fruits et légumes)',
      'Full-day fast': 'Jeûne journée complète',
      'Multi-day fast': 'Jeûne de plusieurs jours',
    },
    es: {
      'Partial fast (sunrise to sunset)': 'Ayuno parcial (del amanecer al atardecer)',
      'Daniel fast (fruits & vegetables)': 'Ayuno de Daniel (frutas y verduras)',
      'Full-day fast': 'Ayuno de día completo',
      'Multi-day fast': 'Ayuno de varios días',
    },
    pcm: {},
    yo: {
      'Partial fast (sunrise to sunset)': 'Àwẹ̀ apá kan (àfi ìlà oòrùn dé àṣálẹ́)',
      'Daniel fast (fruits & vegetables)': 'Àwẹ̀ Dáníẹ́lì (èso àti ewébẹ̀)',
      'Full-day fast': 'Àwẹ̀ ọjọ́ kíkún',
      'Multi-day fast': 'Àwẹ̀ ọjọ́ púpọ̀',
    },
    ig: {
      'Partial fast (sunrise to sunset)': 'Ọbụbụ ọnụ akụkụ (site n\u2019ututu ruo mgbede)',
      'Daniel fast (fruits & vegetables)': 'Ọbụbụ ọnụ Daniel (mkpụrụ osisi na akwụkwọ nri)',
      'Full-day fast': 'Ọbụbụ ọnụ ụbọchị dum',
      'Multi-day fast': 'Ọbụbụ ọnụ ụbọchị ọtụtụ',
    },
  },
  fastingDuration: {
    fr: { '1 day': '1 jour', '3 days': '3 jours', '7 days': '7 jours', '21 days': '21 jours' },
    es: { '1 day': '1 día', '3 days': '3 días', '7 days': '7 días', '21 days': '21 días' },
    pcm: {},
    yo: { '1 day': 'Ọjọ́ 1', '3 days': 'Ọjọ́ 3', '7 days': 'Ọjọ́ 7', '21 days': 'Ọjọ́ 21' },
    ig: { '1 day': 'Ụbọchị 1', '3 days': 'Ụbọchị 3', '7 days': 'Ụbọchị 7', '21 days': 'Ụbọchị 21' },
  },
  itemSource: {
    fr: {
      '🎙 Sermon': '🎙 Sermon',
      '📚 Study Guide': "📚 Guide d'étude",
      '📋 Sunday Pack': '📋 Pack du dimanche',
      '📱 Social Pack': '📱 Pack social',
      '🍽 Fasting Plan': '🍽 Plan de jeûne',
      '🙏 Prayer': '🙏 Prière',
    },
    es: {
      '🎙 Sermon': '🎙 Sermón',
      '📚 Study Guide': '📚 Guía de estudio',
      '📋 Sunday Pack': '📋 Paquete dominical',
      '📱 Social Pack': '📱 Paquete social',
      '🍽 Fasting Plan': '🍽 Plan de ayuno',
      '🙏 Prayer': '🙏 Oración',
    },
    pcm: {},
    yo: {
      '🎙 Sermon': '🎙 Ìwàásù',
      '📚 Study Guide': '📚 Ìtọ́sọ́nà Ìkẹ́kọ̀ọ́',
      '📋 Sunday Pack': '📋 Sunday Pack',
      '📱 Social Pack': '📱 Social Pack',
      '🍽 Fasting Plan': '🍽 Ètò Àwẹ̀',
      '🙏 Prayer': '🙏 Àdúrà',
    },
    ig: {
      '🎙 Sermon': '🎙 Nkwusa',
      '📚 Study Guide': '📚 Ntuziaka Ọmụmụ',
      '📋 Sunday Pack': '📋 Sunday Pack',
      '📱 Social Pack': '📱 Social Pack',
      '🍽 Fasting Plan': '🍽 Atụmatụ Ọbụbụ Ọnụ',
      '🙏 Prayer': '🙏 Ekpere',
    },
  },
  vaultType: {
    fr: {
      '📜 Doctrine / Statement of Faith': '📜 Doctrine / Déclaration de foi',
      '🎯 Vision & Mission': '🎯 Vision et mission',
      '🎙 Previous Sermon Notes': '🎙 Notes de sermons précédents',
      '📘 Teaching / Leadership Manual': '📘 Manuel d\'enseignement / de leadership',
      '🔤 Ministry Terminology': '🔤 Terminologie ministérielle',
      '📄 Other': '📄 Autre',
    },
    es: {
      '📜 Doctrine / Statement of Faith': '📜 Doctrina / Declaración de fe',
      '🎯 Vision & Mission': '🎯 Visión y misión',
      '🎙 Previous Sermon Notes': '🎙 Notas de sermones anteriores',
      '📘 Teaching / Leadership Manual': '📘 Manual de enseñanza / liderazgo',
      '🔤 Ministry Terminology': '🔤 Terminología ministerial',
      '📄 Other': '📄 Otro',
    },
    pcm: {},
    yo: {
      '📜 Doctrine / Statement of Faith': '📜 Ẹ̀kọ́ Ìsìn / Gbólóhùn Ìgbàgbọ́',
      '🎯 Vision & Mission': '🎯 Ìran àti Ìfiránṣẹ́',
      '🎙 Previous Sermon Notes': '🎙 Àkọsílẹ̀ Ìwàásù Àtijọ́',
      '📘 Teaching / Leadership Manual': '📘 Ìwé Ẹ̀kọ́ / Olórí',
      '🔤 Ministry Terminology': '🔤 Ọ̀rọ̀ Iṣẹ́ Ìsìn',
      '📄 Other': '📄 Òmíràn',
    },
    ig: {
      '📜 Doctrine / Statement of Faith': '📜 Ozizi Okpukpe / Nkwupụta Okwukwe',
      '🎯 Vision & Mission': '🎯 Ọhụụ na Ozi',
      '🎙 Previous Sermon Notes': '🎙 Ndetu Nkwusa Gara Aga',
      '📘 Teaching / Leadership Manual': '📘 Akwụkwọ Ozizi / Ndu',
      '🔤 Ministry Terminology': '🔤 Okwu Ozi',
      '📄 Other': '📄 Ọzọ',
    },
  },
  calendarEventType: {
    fr: {
      '⛪ Sunday Service': '⛪ Culte du dimanche',
      '🍽 Fasting Programme': '🍽 Programme de jeûne',
      '🙏 Prayer Meeting': '🙏 Réunion de prière',
      '📌 Other': '📌 Autre',
    },
    es: {
      '⛪ Sunday Service': '⛪ Servicio dominical',
      '🍽 Fasting Programme': '🍽 Programa de ayuno',
      '🙏 Prayer Meeting': '🙏 Reunión de oración',
      '📌 Other': '📌 Otro',
    },
    pcm: {},
    yo: {
      '⛪ Sunday Service': '⛪ Ìsìn Ọjọ́ Ìsinmi',
      '🍽 Fasting Programme': '🍽 Ètò Àwẹ̀',
      '🙏 Prayer Meeting': '🙏 Ìpàdé Àdúrà',
      '📌 Other': '📌 Òmíràn',
    },
    ig: {
      '⛪ Sunday Service': '⛪ Ọrụ Ụbọchị Ụka',
      '🍽 Fasting Programme': '🍽 Atụmatụ Ọbụbụ Ọnụ',
      '🙏 Prayer Meeting': '🙏 Nzukọ Ekpere',
      '📌 Other': '📌 Ọzọ',
    },
  },
}

// translateOption(lang, category, value) -> translated label, or the
// original English value if no translation exists (safe fallback).
export function translateOption(lang, category, value) {
  if (!lang || lang === 'en') return value
  const cat = OPTION_LABELS[category]
  if (!cat) return value
  const table = cat[lang]
  if (!table) return value
  return table[value] || value
}
